name: CICD - Build & Release

on:
  push:
    paths:
      - 'programs/monaco_protocol/**'
    branches: [ develop ]

jobs:
  dev_build:
    uses: BetDexLabs/protocol-private/.github/workflows/ci_build_.yml@develop
    with:
      build_type: dev
      solana_version: ${{ vars.ORG_SOLANA_VERSION }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.ORG_AWS_REGION }}

  stable_build:
    uses: BetDexLabs/protocol-private/.github/workflows/ci_build_.yml@develop
    with:
      build_type: stable
      solana_version: ${{ vars.ORG_SOLANA_VERSION }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.ORG_AWS_REGION }}

  cd_deploy:
    needs: dev_build
    uses: BetDexLabs/protocol-private/.github/workflows/cd_deploy_.yml@develop
    with:
      build: ${{ needs.dev_build.outputs.build_version }}
      environment: devnet
      note: "Auto-Deploy to Devnet"
      solana_version: ${{ vars.ORG_SOLANA_VERSION_DEPLOY }}
    secrets:
      access_key_id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
      access_key: ${{ secrets.ORG_AWS_SECRET_KEY }}
      region: ${{ secrets.ORG_AWS_REGION }}
      wallet_pass: ${{ secrets.ORG_DEV_WALLET_PASSPHRASE }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
